### ISSUE TITLE
I can register as a new user

### ISSUE THREAD

**Issue by AllyMurray** [NorthEastDeveloperNetwork/book-trading-club#3]

**Comment by llbbdd** [comment]
When I tries to register with an email that was already in the database:

A user with the given username is already registered

AuthenticationError
    at /home/leigh/Coding/WebApps/book-trading-club/node_modules/passport-local-mongoose/index.js:244:19
    at /home/leigh/Coding/WebApps/book-trading-club/node_modules/mongoose/lib/query.js:2839:18
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by AllyMurray** [comment]
Fix pushed straight to the development branch for this.

**Comment by llbbdd** [comment]
Tested and comment
